### ISSUE TITLE
 "submitted 4 hours ago"

### ISSUE THREAD

**Issue by stuartyeates** [danielBingham/peerreview#136]
**Describe the bug**
The server appears to have a time bug, probably a timezone bug

**To Reproduce**
1. Submit a draft from a browser in "Auckland/New Zealand" timezone 
2. Immediately after hitting submit the draft is displayed, but was "submitted 4 hours ago"

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10471/199630052-cd060661-fb37-4332-9fc7-2bcc94dd7461.png)

**Comment by danielBingham** [comment]
Yep.  That's a bug all right.  I'll look into it.  Thanks!
