### ISSUE TITLE
Code license?

### ISSUE THREAD

**Issue by mlinksva** [danielBingham/peerreview#76]
**Describe the bug**

https://blog.peer-review.io/we-might-have-a-way-to-fix-scientific-publishing says "Peer Review is being developed open source" but there's no indication of which open source license the code is under.

**To Reproduce**
1. Go to https://github.com/danielBingham/peerreview
2. Look for license indications (eg LICENSE file, package field, README statement) and find none

**Expected behavior**
Expect there to be a LICENSE or similar file with text of whatever open source license the project's code is under.

**Additional context**
I read the blog post after seeing it linked from https://news.ycombinator.com/item?id=32376133

**Comment by danielBingham** [comment]
Good call.  I should have chosen a license prior to posting that, thank you for reminding me.  I'm still debating which license.  I'm stuck between totally open license like MIT and a copy left license.  I might start with copy left, we can always replace it with a more open one in the future.

**Comment by danielBingham** [comment]
License deployed - went with GPL 3.0 for now.  Might switch to MIT or Apache in the future, but for now, if someone wants to fork the project, I'd prefer they keep it open source in order to stick to the goals and ethos of the project.
